// Generated by gencpp from file arm_state/state.msg
// DO NOT EDIT!


#ifndef ARM_STATE_MESSAGE_STATE_H
#define ARM_STATE_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_state
{
template <class ContainerAllocator>
struct state_
{
  typedef state_<ContainerAllocator> Type;

  state_()
    : id()
    , position()
    , angle()  {
    }
  state_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , position(_alloc)
    , angle(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _id_type;
  _id_type id;

   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _position_type;
  _position_type position;

   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::arm_state::state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_state::state_<ContainerAllocator> const> ConstPtr;

}; // struct state_

typedef ::arm_state::state_<std::allocator<void> > state;

typedef boost::shared_ptr< ::arm_state::state > statePtr;
typedef boost::shared_ptr< ::arm_state::state const> stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_state::state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_state::state_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arm_state

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'arm_state': ['/home/kou256/ROS/EnterZen/src/arm_state/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arm_state::state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_state::state_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_state::state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_state::state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_state::state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_state::state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_state::state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc5377a64d7ce3f6a03aaa672d3115bd";
  }

  static const char* value(const ::arm_state::state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc5377a64d7ce3f6ULL;
  static const uint64_t static_value2 = 0xa03aaa672d3115bdULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_state::state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_state/state";
  }

  static const char* value(const ::arm_state::state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_state::state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] id\n\
uint16[] position\n\
uint16[] angle\n\
";
  }

  static const char* value(const ::arm_state::state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_state::state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.position);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_state::state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_state::state_<ContainerAllocator>& v)
  {
    s << indent << "id[]" << std::endl;
    for (size_t i = 0; i < v.id.size(); ++i)
    {
      s << indent << "  id[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.id[i]);
    }
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "angle[]" << std::endl;
    for (size_t i = 0; i < v.angle.size(); ++i)
    {
      s << indent << "  angle[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.angle[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_STATE_MESSAGE_STATE_H
