#ifndef ENTERZEN_JOY_HPP
#define ENTERZEN_JOY_HPP

enum EAxes {
    LEFT_STICK_HOR,
    LEFT_STICK_VER,
    LEFT_TRIGER,
    RIGHT_STICK_HOR,
    RIGHT_STICK_VER,
    RIGHT_TRIGER,
    CROSS_BUTTON_HOR,
    CROSS_BUTTON_VER,
};

#endif